

// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!



#include <stdbool.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
	// We also try to prevent mixing versions of shared uniffi header structs.
	// If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V6
	#ifndef UNIFFI_SHARED_HEADER_V6
		#error Combining helper code from multiple versions of uniffi is not supported
	#endif // ndef UNIFFI_SHARED_HEADER_V6
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V6
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V6 in this file.           ⚠️

typedef struct RustBuffer {
	uint64_t capacity;
	uint64_t len;
	uint8_t *data;
} RustBuffer;

typedef struct ForeignBytes {
	int32_t len;
	const uint8_t *data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
	int8_t code;
	RustBuffer errorBuf;
} RustCallStatus;

#endif // UNIFFI_SHARED_H


#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t data, int8_t poll_result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiRustFutureContinuationCallback(
				UniffiRustFutureContinuationCallback cb, uint64_t data, int8_t poll_result)
{
	return cb(data, poll_result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t handle);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureFree(
				UniffiForeignFutureFree cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t handle);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceFree(
				UniffiCallbackInterfaceFree cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t callback_data, UniffiForeignFutureStructU8 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU8(
				UniffiForeignFutureCompleteU8 cb, uint64_t callback_data, UniffiForeignFutureStructU8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t callback_data, UniffiForeignFutureStructI8 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI8(
				UniffiForeignFutureCompleteI8 cb, uint64_t callback_data, UniffiForeignFutureStructI8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t callback_data, UniffiForeignFutureStructU16 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU16(
				UniffiForeignFutureCompleteU16 cb, uint64_t callback_data, UniffiForeignFutureStructU16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t callback_data, UniffiForeignFutureStructI16 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI16(
				UniffiForeignFutureCompleteI16 cb, uint64_t callback_data, UniffiForeignFutureStructI16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t callback_data, UniffiForeignFutureStructU32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU32(
				UniffiForeignFutureCompleteU32 cb, uint64_t callback_data, UniffiForeignFutureStructU32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t callback_data, UniffiForeignFutureStructI32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI32(
				UniffiForeignFutureCompleteI32 cb, uint64_t callback_data, UniffiForeignFutureStructI32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t callback_data, UniffiForeignFutureStructU64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU64(
				UniffiForeignFutureCompleteU64 cb, uint64_t callback_data, UniffiForeignFutureStructU64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t callback_data, UniffiForeignFutureStructI64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI64(
				UniffiForeignFutureCompleteI64 cb, uint64_t callback_data, UniffiForeignFutureStructI64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t callback_data, UniffiForeignFutureStructF32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF32(
				UniffiForeignFutureCompleteF32 cb, uint64_t callback_data, UniffiForeignFutureStructF32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t callback_data, UniffiForeignFutureStructF64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF64(
				UniffiForeignFutureCompleteF64 cb, uint64_t callback_data, UniffiForeignFutureStructF64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void* returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t callback_data, UniffiForeignFutureStructPointer result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompletePointer(
				UniffiForeignFutureCompletePointer cb, uint64_t callback_data, UniffiForeignFutureStructPointer result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t callback_data, UniffiForeignFutureStructRustBuffer result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteRustBuffer(
				UniffiForeignFutureCompleteRustBuffer cb, uint64_t callback_data, UniffiForeignFutureStructRustBuffer result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t callback_data, UniffiForeignFutureStructVoid result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteVoid(
				UniffiForeignFutureCompleteVoid cb, uint64_t callback_data, UniffiForeignFutureStructVoid result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_CLONE_ANCHORS
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_CLONE_ANCHORS
void* uniffi_libveritas_uniffi_fn_clone_anchors(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FREE_ANCHORS
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FREE_ANCHORS
void uniffi_libveritas_uniffi_fn_free_anchors(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_CONSTRUCTOR_ANCHORS_FROM_JSON
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_CONSTRUCTOR_ANCHORS_FROM_JSON
void* uniffi_libveritas_uniffi_fn_constructor_anchors_from_json(RustBuffer json, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_ANCHORS_COMPUTE_ANCHOR_SET_HASH
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_ANCHORS_COMPUTE_ANCHOR_SET_HASH
RustBuffer uniffi_libveritas_uniffi_fn_method_anchors_compute_anchor_set_hash(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_CLONE_LOOKUP
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_CLONE_LOOKUP
void* uniffi_libveritas_uniffi_fn_clone_lookup(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FREE_LOOKUP
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FREE_LOOKUP
void uniffi_libveritas_uniffi_fn_free_lookup(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_CONSTRUCTOR_LOOKUP_NEW
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_CONSTRUCTOR_LOOKUP_NEW
void* uniffi_libveritas_uniffi_fn_constructor_lookup_new(RustBuffer names, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_LOOKUP_ADVANCE
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_LOOKUP_ADVANCE
RustBuffer uniffi_libveritas_uniffi_fn_method_lookup_advance(void* ptr, RustBuffer zones, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_LOOKUP_EXPAND_ZONES
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_LOOKUP_EXPAND_ZONES
RustBuffer uniffi_libveritas_uniffi_fn_method_lookup_expand_zones(void* ptr, RustBuffer zones, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_LOOKUP_START
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_LOOKUP_START
RustBuffer uniffi_libveritas_uniffi_fn_method_lookup_start(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_CLONE_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_CLONE_MESSAGE
void* uniffi_libveritas_uniffi_fn_clone_message(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FREE_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FREE_MESSAGE
void uniffi_libveritas_uniffi_fn_free_message(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_CONSTRUCTOR_MESSAGE_NEW
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_CONSTRUCTOR_MESSAGE_NEW
void* uniffi_libveritas_uniffi_fn_constructor_message_new(RustBuffer bytes, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_MESSAGE_TO_BYTES
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_MESSAGE_TO_BYTES
RustBuffer uniffi_libveritas_uniffi_fn_method_message_to_bytes(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_MESSAGE_UPDATE
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_MESSAGE_UPDATE
void uniffi_libveritas_uniffi_fn_method_message_update(void* ptr, RustBuffer updates, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_CLONE_MESSAGEBUILDER
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_CLONE_MESSAGEBUILDER
void* uniffi_libveritas_uniffi_fn_clone_messagebuilder(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FREE_MESSAGEBUILDER
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FREE_MESSAGEBUILDER
void uniffi_libveritas_uniffi_fn_free_messagebuilder(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_CONSTRUCTOR_MESSAGEBUILDER_NEW
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_CONSTRUCTOR_MESSAGEBUILDER_NEW
void* uniffi_libveritas_uniffi_fn_constructor_messagebuilder_new(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_MESSAGEBUILDER_ADD_CERT
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_MESSAGEBUILDER_ADD_CERT
void uniffi_libveritas_uniffi_fn_method_messagebuilder_add_cert(void* ptr, RustBuffer cert_bytes, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_MESSAGEBUILDER_ADD_CHAIN
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_MESSAGEBUILDER_ADD_CHAIN
void uniffi_libveritas_uniffi_fn_method_messagebuilder_add_chain(void* ptr, RustBuffer chain_bytes, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_MESSAGEBUILDER_ADD_HANDLE
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_MESSAGEBUILDER_ADD_HANDLE
void uniffi_libveritas_uniffi_fn_method_messagebuilder_add_handle(void* ptr, RustBuffer chain_bytes, RustBuffer records_bytes, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_MESSAGEBUILDER_ADD_RECORDS
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_MESSAGEBUILDER_ADD_RECORDS
void uniffi_libveritas_uniffi_fn_method_messagebuilder_add_records(void* ptr, RustBuffer handle, RustBuffer records_bytes, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_MESSAGEBUILDER_ADD_UPDATE
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_MESSAGEBUILDER_ADD_UPDATE
void uniffi_libveritas_uniffi_fn_method_messagebuilder_add_update(void* ptr, RustBuffer entry, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_MESSAGEBUILDER_BUILD
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_MESSAGEBUILDER_BUILD
void* uniffi_libveritas_uniffi_fn_method_messagebuilder_build(void* ptr, RustBuffer chain_proof, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_MESSAGEBUILDER_CHAIN_PROOF_REQUEST
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_MESSAGEBUILDER_CHAIN_PROOF_REQUEST
RustBuffer uniffi_libveritas_uniffi_fn_method_messagebuilder_chain_proof_request(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_CLONE_QUERYCONTEXT
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_CLONE_QUERYCONTEXT
void* uniffi_libveritas_uniffi_fn_clone_querycontext(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FREE_QUERYCONTEXT
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FREE_QUERYCONTEXT
void uniffi_libveritas_uniffi_fn_free_querycontext(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_CONSTRUCTOR_QUERYCONTEXT_NEW
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_CONSTRUCTOR_QUERYCONTEXT_NEW
void* uniffi_libveritas_uniffi_fn_constructor_querycontext_new(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_QUERYCONTEXT_ADD_REQUEST
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_QUERYCONTEXT_ADD_REQUEST
void uniffi_libveritas_uniffi_fn_method_querycontext_add_request(void* ptr, RustBuffer handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_QUERYCONTEXT_ADD_ZONE
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_QUERYCONTEXT_ADD_ZONE
void uniffi_libveritas_uniffi_fn_method_querycontext_add_zone(void* ptr, RustBuffer zone_bytes, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_CLONE_RECORDSET
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_CLONE_RECORDSET
void* uniffi_libveritas_uniffi_fn_clone_recordset(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FREE_RECORDSET
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FREE_RECORDSET
void uniffi_libveritas_uniffi_fn_free_recordset(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_CONSTRUCTOR_RECORDSET_NEW
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_CONSTRUCTOR_RECORDSET_NEW
void* uniffi_libveritas_uniffi_fn_constructor_recordset_new(RustBuffer data, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_CONSTRUCTOR_RECORDSET_PACK
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_CONSTRUCTOR_RECORDSET_PACK
void* uniffi_libveritas_uniffi_fn_constructor_recordset_pack(RustBuffer records, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_RECORDSET_IS_EMPTY
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_RECORDSET_IS_EMPTY
int8_t uniffi_libveritas_uniffi_fn_method_recordset_is_empty(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_RECORDSET_SIGNING_ID
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_RECORDSET_SIGNING_ID
RustBuffer uniffi_libveritas_uniffi_fn_method_recordset_signing_id(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_RECORDSET_TO_BYTES
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_RECORDSET_TO_BYTES
RustBuffer uniffi_libveritas_uniffi_fn_method_recordset_to_bytes(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_RECORDSET_UNPACK
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_RECORDSET_UNPACK
RustBuffer uniffi_libveritas_uniffi_fn_method_recordset_unpack(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_CLONE_VERIFIEDMESSAGE
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_CLONE_VERIFIEDMESSAGE
void* uniffi_libveritas_uniffi_fn_clone_verifiedmessage(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FREE_VERIFIEDMESSAGE
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FREE_VERIFIEDMESSAGE
void uniffi_libveritas_uniffi_fn_free_verifiedmessage(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_VERIFIEDMESSAGE_CERTIFICATES
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_VERIFIEDMESSAGE_CERTIFICATES
RustBuffer uniffi_libveritas_uniffi_fn_method_verifiedmessage_certificates(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_VERIFIEDMESSAGE_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_VERIFIEDMESSAGE_MESSAGE
void* uniffi_libveritas_uniffi_fn_method_verifiedmessage_message(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_VERIFIEDMESSAGE_MESSAGE_BYTES
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_VERIFIEDMESSAGE_MESSAGE_BYTES
RustBuffer uniffi_libveritas_uniffi_fn_method_verifiedmessage_message_bytes(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_VERIFIEDMESSAGE_ZONES
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_VERIFIEDMESSAGE_ZONES
RustBuffer uniffi_libveritas_uniffi_fn_method_verifiedmessage_zones(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_CLONE_VERITAS
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_CLONE_VERITAS
void* uniffi_libveritas_uniffi_fn_clone_veritas(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FREE_VERITAS
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FREE_VERITAS
void uniffi_libveritas_uniffi_fn_free_veritas(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_CONSTRUCTOR_VERITAS_NEW
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_CONSTRUCTOR_VERITAS_NEW
void* uniffi_libveritas_uniffi_fn_constructor_veritas_new(void* anchors, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_VERITAS_COMPUTE_ANCHOR_SET_HASH
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_VERITAS_COMPUTE_ANCHOR_SET_HASH
RustBuffer uniffi_libveritas_uniffi_fn_method_veritas_compute_anchor_set_hash(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_VERITAS_IS_FINALIZED
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_VERITAS_IS_FINALIZED
int8_t uniffi_libveritas_uniffi_fn_method_veritas_is_finalized(void* ptr, uint32_t commitment_height, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_VERITAS_NEWEST_ANCHOR
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_VERITAS_NEWEST_ANCHOR
uint32_t uniffi_libveritas_uniffi_fn_method_veritas_newest_anchor(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_VERITAS_OLDEST_ANCHOR
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_VERITAS_OLDEST_ANCHOR
uint32_t uniffi_libveritas_uniffi_fn_method_veritas_oldest_anchor(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_VERITAS_SOVEREIGNTY_FOR
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_VERITAS_SOVEREIGNTY_FOR
RustBuffer uniffi_libveritas_uniffi_fn_method_veritas_sovereignty_for(void* ptr, uint32_t commitment_height, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_VERITAS_VERIFY
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_VERITAS_VERIFY
void* uniffi_libveritas_uniffi_fn_method_veritas_verify(void* ptr, void* ctx, void* msg, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_VERITAS_VERIFY_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_METHOD_VERITAS_VERIFY_WITH_OPTIONS
void* uniffi_libveritas_uniffi_fn_method_veritas_verify_with_options(void* ptr, void* ctx, void* msg, uint32_t options, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FUNC_CREATE_CERTIFICATE_CHAIN
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FUNC_CREATE_CERTIFICATE_CHAIN
RustBuffer uniffi_libveritas_uniffi_fn_func_create_certificate_chain(RustBuffer subject, RustBuffer cert_bytes_list, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FUNC_CREATE_OFFCHAIN_RECORDS
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FUNC_CREATE_OFFCHAIN_RECORDS
RustBuffer uniffi_libveritas_uniffi_fn_func_create_offchain_records(void* record_set, RustBuffer signature, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FUNC_DECODE_CERTIFICATE
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FUNC_DECODE_CERTIFICATE
RustBuffer uniffi_libveritas_uniffi_fn_func_decode_certificate(RustBuffer bytes, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FUNC_DECODE_ZONE
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FUNC_DECODE_ZONE
RustBuffer uniffi_libveritas_uniffi_fn_func_decode_zone(RustBuffer bytes, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FUNC_HASH_SIGNABLE_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FUNC_HASH_SIGNABLE_MESSAGE
RustBuffer uniffi_libveritas_uniffi_fn_func_hash_signable_message(RustBuffer msg, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FUNC_VERIFY_DEFAULT
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FUNC_VERIFY_DEFAULT
uint32_t uniffi_libveritas_uniffi_fn_func_verify_default(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FUNC_VERIFY_DEV_MODE
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FUNC_VERIFY_DEV_MODE
uint32_t uniffi_libveritas_uniffi_fn_func_verify_dev_mode(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FUNC_VERIFY_ENABLE_SNARK
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FUNC_VERIFY_ENABLE_SNARK
uint32_t uniffi_libveritas_uniffi_fn_func_verify_enable_snark(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FUNC_VERIFY_SCHNORR
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FUNC_VERIFY_SCHNORR
void uniffi_libveritas_uniffi_fn_func_verify_schnorr(RustBuffer msg_hash, RustBuffer signature, RustBuffer pubkey, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FUNC_VERIFY_SPACES_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FUNC_VERIFY_SPACES_MESSAGE
void uniffi_libveritas_uniffi_fn_func_verify_spaces_message(RustBuffer msg, RustBuffer signature, RustBuffer pubkey, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FUNC_ZONE_IS_BETTER_THAN
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FUNC_ZONE_IS_BETTER_THAN
int8_t uniffi_libveritas_uniffi_fn_func_zone_is_better_than(RustBuffer a, RustBuffer b, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FUNC_ZONE_TO_BYTES
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FUNC_ZONE_TO_BYTES
RustBuffer uniffi_libveritas_uniffi_fn_func_zone_to_bytes(RustBuffer zone, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FUNC_ZONE_TO_JSON
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_FN_FUNC_ZONE_TO_JSON
RustBuffer uniffi_libveritas_uniffi_fn_func_zone_to_json(RustBuffer zone, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUSTBUFFER_ALLOC
RustBuffer ffi_libveritas_uniffi_rustbuffer_alloc(uint64_t size, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_libveritas_uniffi_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUSTBUFFER_FREE
void ffi_libveritas_uniffi_rustbuffer_free(RustBuffer buf, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUSTBUFFER_RESERVE
RustBuffer ffi_libveritas_uniffi_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_POLL_U8
void ffi_libveritas_uniffi_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_CANCEL_U8
void ffi_libveritas_uniffi_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_FREE_U8
void ffi_libveritas_uniffi_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_libveritas_uniffi_rust_future_complete_u8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_POLL_I8
void ffi_libveritas_uniffi_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_CANCEL_I8
void ffi_libveritas_uniffi_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_FREE_I8
void ffi_libveritas_uniffi_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_COMPLETE_I8
int8_t ffi_libveritas_uniffi_rust_future_complete_i8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_POLL_U16
void ffi_libveritas_uniffi_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_CANCEL_U16
void ffi_libveritas_uniffi_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_FREE_U16
void ffi_libveritas_uniffi_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_libveritas_uniffi_rust_future_complete_u16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_POLL_I16
void ffi_libveritas_uniffi_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_CANCEL_I16
void ffi_libveritas_uniffi_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_FREE_I16
void ffi_libveritas_uniffi_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_COMPLETE_I16
int16_t ffi_libveritas_uniffi_rust_future_complete_i16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_POLL_U32
void ffi_libveritas_uniffi_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_CANCEL_U32
void ffi_libveritas_uniffi_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_FREE_U32
void ffi_libveritas_uniffi_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_libveritas_uniffi_rust_future_complete_u32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_POLL_I32
void ffi_libveritas_uniffi_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_CANCEL_I32
void ffi_libveritas_uniffi_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_FREE_I32
void ffi_libveritas_uniffi_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_COMPLETE_I32
int32_t ffi_libveritas_uniffi_rust_future_complete_i32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_POLL_U64
void ffi_libveritas_uniffi_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_CANCEL_U64
void ffi_libveritas_uniffi_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_FREE_U64
void ffi_libveritas_uniffi_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_libveritas_uniffi_rust_future_complete_u64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_POLL_I64
void ffi_libveritas_uniffi_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_CANCEL_I64
void ffi_libveritas_uniffi_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_FREE_I64
void ffi_libveritas_uniffi_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_COMPLETE_I64
int64_t ffi_libveritas_uniffi_rust_future_complete_i64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_POLL_F32
void ffi_libveritas_uniffi_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_CANCEL_F32
void ffi_libveritas_uniffi_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_FREE_F32
void ffi_libveritas_uniffi_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_COMPLETE_F32
float ffi_libveritas_uniffi_rust_future_complete_f32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_POLL_F64
void ffi_libveritas_uniffi_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_CANCEL_F64
void ffi_libveritas_uniffi_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_FREE_F64
void ffi_libveritas_uniffi_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_COMPLETE_F64
double ffi_libveritas_uniffi_rust_future_complete_f64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_POLL_POINTER
void ffi_libveritas_uniffi_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_CANCEL_POINTER
void ffi_libveritas_uniffi_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_FREE_POINTER
void ffi_libveritas_uniffi_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_COMPLETE_POINTER
void* ffi_libveritas_uniffi_rust_future_complete_pointer(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_libveritas_uniffi_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_libveritas_uniffi_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_libveritas_uniffi_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_libveritas_uniffi_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_POLL_VOID
void ffi_libveritas_uniffi_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_CANCEL_VOID
void ffi_libveritas_uniffi_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_FREE_VOID
void ffi_libveritas_uniffi_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_RUST_FUTURE_COMPLETE_VOID
void ffi_libveritas_uniffi_rust_future_complete_void(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_FUNC_CREATE_CERTIFICATE_CHAIN
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_FUNC_CREATE_CERTIFICATE_CHAIN
uint16_t uniffi_libveritas_uniffi_checksum_func_create_certificate_chain(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_FUNC_CREATE_OFFCHAIN_RECORDS
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_FUNC_CREATE_OFFCHAIN_RECORDS
uint16_t uniffi_libveritas_uniffi_checksum_func_create_offchain_records(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_FUNC_DECODE_CERTIFICATE
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_FUNC_DECODE_CERTIFICATE
uint16_t uniffi_libveritas_uniffi_checksum_func_decode_certificate(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_FUNC_DECODE_ZONE
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_FUNC_DECODE_ZONE
uint16_t uniffi_libveritas_uniffi_checksum_func_decode_zone(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_FUNC_HASH_SIGNABLE_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_FUNC_HASH_SIGNABLE_MESSAGE
uint16_t uniffi_libveritas_uniffi_checksum_func_hash_signable_message(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_FUNC_VERIFY_DEFAULT
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_FUNC_VERIFY_DEFAULT
uint16_t uniffi_libveritas_uniffi_checksum_func_verify_default(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_FUNC_VERIFY_DEV_MODE
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_FUNC_VERIFY_DEV_MODE
uint16_t uniffi_libveritas_uniffi_checksum_func_verify_dev_mode(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_FUNC_VERIFY_ENABLE_SNARK
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_FUNC_VERIFY_ENABLE_SNARK
uint16_t uniffi_libveritas_uniffi_checksum_func_verify_enable_snark(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_FUNC_VERIFY_SCHNORR
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_FUNC_VERIFY_SCHNORR
uint16_t uniffi_libveritas_uniffi_checksum_func_verify_schnorr(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_FUNC_VERIFY_SPACES_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_FUNC_VERIFY_SPACES_MESSAGE
uint16_t uniffi_libveritas_uniffi_checksum_func_verify_spaces_message(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_FUNC_ZONE_IS_BETTER_THAN
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_FUNC_ZONE_IS_BETTER_THAN
uint16_t uniffi_libveritas_uniffi_checksum_func_zone_is_better_than(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_FUNC_ZONE_TO_BYTES
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_FUNC_ZONE_TO_BYTES
uint16_t uniffi_libveritas_uniffi_checksum_func_zone_to_bytes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_FUNC_ZONE_TO_JSON
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_FUNC_ZONE_TO_JSON
uint16_t uniffi_libveritas_uniffi_checksum_func_zone_to_json(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_ANCHORS_COMPUTE_ANCHOR_SET_HASH
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_ANCHORS_COMPUTE_ANCHOR_SET_HASH
uint16_t uniffi_libveritas_uniffi_checksum_method_anchors_compute_anchor_set_hash(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_LOOKUP_ADVANCE
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_LOOKUP_ADVANCE
uint16_t uniffi_libveritas_uniffi_checksum_method_lookup_advance(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_LOOKUP_EXPAND_ZONES
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_LOOKUP_EXPAND_ZONES
uint16_t uniffi_libveritas_uniffi_checksum_method_lookup_expand_zones(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_LOOKUP_START
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_LOOKUP_START
uint16_t uniffi_libveritas_uniffi_checksum_method_lookup_start(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_MESSAGE_TO_BYTES
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_MESSAGE_TO_BYTES
uint16_t uniffi_libveritas_uniffi_checksum_method_message_to_bytes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_MESSAGE_UPDATE
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_MESSAGE_UPDATE
uint16_t uniffi_libveritas_uniffi_checksum_method_message_update(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_MESSAGEBUILDER_ADD_CERT
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_MESSAGEBUILDER_ADD_CERT
uint16_t uniffi_libveritas_uniffi_checksum_method_messagebuilder_add_cert(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_MESSAGEBUILDER_ADD_CHAIN
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_MESSAGEBUILDER_ADD_CHAIN
uint16_t uniffi_libveritas_uniffi_checksum_method_messagebuilder_add_chain(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_MESSAGEBUILDER_ADD_HANDLE
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_MESSAGEBUILDER_ADD_HANDLE
uint16_t uniffi_libveritas_uniffi_checksum_method_messagebuilder_add_handle(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_MESSAGEBUILDER_ADD_RECORDS
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_MESSAGEBUILDER_ADD_RECORDS
uint16_t uniffi_libveritas_uniffi_checksum_method_messagebuilder_add_records(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_MESSAGEBUILDER_ADD_UPDATE
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_MESSAGEBUILDER_ADD_UPDATE
uint16_t uniffi_libveritas_uniffi_checksum_method_messagebuilder_add_update(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_MESSAGEBUILDER_BUILD
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_MESSAGEBUILDER_BUILD
uint16_t uniffi_libveritas_uniffi_checksum_method_messagebuilder_build(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_MESSAGEBUILDER_CHAIN_PROOF_REQUEST
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_MESSAGEBUILDER_CHAIN_PROOF_REQUEST
uint16_t uniffi_libveritas_uniffi_checksum_method_messagebuilder_chain_proof_request(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_QUERYCONTEXT_ADD_REQUEST
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_QUERYCONTEXT_ADD_REQUEST
uint16_t uniffi_libveritas_uniffi_checksum_method_querycontext_add_request(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_QUERYCONTEXT_ADD_ZONE
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_QUERYCONTEXT_ADD_ZONE
uint16_t uniffi_libveritas_uniffi_checksum_method_querycontext_add_zone(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_RECORDSET_IS_EMPTY
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_RECORDSET_IS_EMPTY
uint16_t uniffi_libveritas_uniffi_checksum_method_recordset_is_empty(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_RECORDSET_SIGNING_ID
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_RECORDSET_SIGNING_ID
uint16_t uniffi_libveritas_uniffi_checksum_method_recordset_signing_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_RECORDSET_TO_BYTES
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_RECORDSET_TO_BYTES
uint16_t uniffi_libveritas_uniffi_checksum_method_recordset_to_bytes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_RECORDSET_UNPACK
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_RECORDSET_UNPACK
uint16_t uniffi_libveritas_uniffi_checksum_method_recordset_unpack(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_VERIFIEDMESSAGE_CERTIFICATES
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_VERIFIEDMESSAGE_CERTIFICATES
uint16_t uniffi_libveritas_uniffi_checksum_method_verifiedmessage_certificates(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_VERIFIEDMESSAGE_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_VERIFIEDMESSAGE_MESSAGE
uint16_t uniffi_libveritas_uniffi_checksum_method_verifiedmessage_message(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_VERIFIEDMESSAGE_MESSAGE_BYTES
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_VERIFIEDMESSAGE_MESSAGE_BYTES
uint16_t uniffi_libveritas_uniffi_checksum_method_verifiedmessage_message_bytes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_VERIFIEDMESSAGE_ZONES
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_VERIFIEDMESSAGE_ZONES
uint16_t uniffi_libveritas_uniffi_checksum_method_verifiedmessage_zones(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_VERITAS_COMPUTE_ANCHOR_SET_HASH
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_VERITAS_COMPUTE_ANCHOR_SET_HASH
uint16_t uniffi_libveritas_uniffi_checksum_method_veritas_compute_anchor_set_hash(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_VERITAS_IS_FINALIZED
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_VERITAS_IS_FINALIZED
uint16_t uniffi_libveritas_uniffi_checksum_method_veritas_is_finalized(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_VERITAS_NEWEST_ANCHOR
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_VERITAS_NEWEST_ANCHOR
uint16_t uniffi_libveritas_uniffi_checksum_method_veritas_newest_anchor(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_VERITAS_OLDEST_ANCHOR
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_VERITAS_OLDEST_ANCHOR
uint16_t uniffi_libveritas_uniffi_checksum_method_veritas_oldest_anchor(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_VERITAS_SOVEREIGNTY_FOR
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_VERITAS_SOVEREIGNTY_FOR
uint16_t uniffi_libveritas_uniffi_checksum_method_veritas_sovereignty_for(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_VERITAS_VERIFY
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_VERITAS_VERIFY
uint16_t uniffi_libveritas_uniffi_checksum_method_veritas_verify(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_VERITAS_VERIFY_WITH_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_METHOD_VERITAS_VERIFY_WITH_OPTIONS
uint16_t uniffi_libveritas_uniffi_checksum_method_veritas_verify_with_options(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_CONSTRUCTOR_ANCHORS_FROM_JSON
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_CONSTRUCTOR_ANCHORS_FROM_JSON
uint16_t uniffi_libveritas_uniffi_checksum_constructor_anchors_from_json(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_CONSTRUCTOR_LOOKUP_NEW
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_CONSTRUCTOR_LOOKUP_NEW
uint16_t uniffi_libveritas_uniffi_checksum_constructor_lookup_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_CONSTRUCTOR_MESSAGE_NEW
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_CONSTRUCTOR_MESSAGE_NEW
uint16_t uniffi_libveritas_uniffi_checksum_constructor_message_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_CONSTRUCTOR_MESSAGEBUILDER_NEW
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_CONSTRUCTOR_MESSAGEBUILDER_NEW
uint16_t uniffi_libveritas_uniffi_checksum_constructor_messagebuilder_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_CONSTRUCTOR_QUERYCONTEXT_NEW
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_CONSTRUCTOR_QUERYCONTEXT_NEW
uint16_t uniffi_libveritas_uniffi_checksum_constructor_querycontext_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_CONSTRUCTOR_RECORDSET_NEW
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_CONSTRUCTOR_RECORDSET_NEW
uint16_t uniffi_libveritas_uniffi_checksum_constructor_recordset_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_CONSTRUCTOR_RECORDSET_PACK
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_CONSTRUCTOR_RECORDSET_PACK
uint16_t uniffi_libveritas_uniffi_checksum_constructor_recordset_pack(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_CONSTRUCTOR_VERITAS_NEW
#define UNIFFI_FFIDEF_UNIFFI_LIBVERITAS_UNIFFI_CHECKSUM_CONSTRUCTOR_VERITAS_NEW
uint16_t uniffi_libveritas_uniffi_checksum_constructor_veritas_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_LIBVERITAS_UNIFFI_UNIFFI_CONTRACT_VERSION
uint32_t ffi_libveritas_uniffi_uniffi_contract_version(void
    
);
#endif

